<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Account_Service_Flyin_SignUp"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="0.733">
  <properties />
            <testcase name="signupV1" time="0.336" classname="accountsAPI.Account_Service_Flyin_Signup">
                <failure type="junit.framework.AssertionFailedError"
                  message="(null)"
              >
<![CDATA[junit.framework.AssertionFailedError
  junit.framework.Assert.fail(Assert.java:48)
  junit.framework.Assert.assertTrue(Assert.java:20)
  junit.framework.Assert.assertTrue(Assert.java:27)
  accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
  accountsAPI.Account_Service_Flyin_Signup.signupV1(Account_Service_Flyin_Signup.java:24)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.retryFailed(Invoker.java:839)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
            <testcase name="signupV1" time="0.0" classname="accountsAPI.Account_Service_Flyin_Signup">
          <skipped />
    </testcase>
  
  
</testsuite>
