<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="sysadm-IT3407" name="paymentsUI.PaymentUI_Validation" tests="11" failures="1" timestamp="25 Mar 2020 13:59:22 GMT" time="140.409" errors="0">
  <testcase name="getPayURL" time="0.505" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="firePaymentURLandValidatePaymentModes" time="27.518" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="emptyCreditCardErrorValidation" time="0.552" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="emptyDebitCardErrorValidation" time="0.339" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="authenticateVariousDetails" time="20.045" classname="paymentsUI.PaymentUI_Validation">
    <failure type="junit.framework.AssertionFailedError" message="Section Name is not valid">
      <![CDATA[junit.framework.AssertionFailedError: Section Name is not valid
at junit.framework.Assert.fail(Assert.java:50)
at junit.framework.Assert.assertTrue(Assert.java:20)
at domains.PaymentNodeJS.validateSectionDetails(PaymentNodeJS.java:1612)
at paymentsUI.PaymentUI_Validation.authenticateVariousDetails(PaymentUI_Validation.java:185)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- authenticateVariousDetails -->
  <testcase name="licenseAgreementPolicy" time="5.368" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="imagesAndText" time="0.257" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="validateInvalidExpiry" time="24.308" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="validateInvalidCvv" time="16.800" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="secondRetryMakePayment" time="44.717" classname="paymentsUI.PaymentUI_Validation"/>
  <testcase name="footerLinks" classname="paymentsUI.PaymentUI_Validation">
    <skipped/>
  </testcase> <!-- footerLinks -->
</testsuite> <!-- paymentsUI.PaymentUI_Validation -->
