<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testScriptsHQUI.HQRewardReport" tests="2" time="320.408" ignored="0" failures="1" timestamp="11 Mar 2019 06:31:20 GMT" skipped="1" hostname="sysadm-PC" errors="0">
  <testcase name="rewardReportSanity_117" time="180.615" classname="testScriptsHQUI.HQRewardReport">
    <skipped/>
  </testcase> <!-- rewardReportSanity_117 -->
  <testcase name="rewardReportSanity_117" time="139.793" classname="testScriptsHQUI.HQRewardReport">
    <failure type="java.lang.AssertionError" message="Failure! Element not Visible!">
      <![CDATA[java.lang.AssertionError: Failure! Element not Visible!
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at commonServices.WrapperMethod.elementPresent(WrapperMethod.java:943)
	at commonServices.WrapperMethod.getText(WrapperMethod.java:1699)
	at testScriptsHQUI.HQRewardReport.rewardReportSanity_117(HQRewardReport.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- rewardReportSanity_117 -->
</testsuite> <!-- testScriptsHQUI.HQRewardReport -->
