<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.cleartrip.platform.accounts.API_IVR_Mobile_Date" tests="2" time="161.260" ignored="0" failures="1" timestamp="12 Mar 2019 06:12:10 GMT" skipped="1" hostname="sysadm-PC" errors="0">
  <testcase name="IVR_Date" time="38.370" classname="com.cleartrip.platform.accounts.API_IVR_Mobile_Date">
    <skipped/>
  </testcase> <!-- IVR_Date -->
  <testcase name="IVR_Date" time="122.890" classname="com.cleartrip.platform.accounts.API_IVR_Mobile_Date">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:48)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at junit.framework.Assert.assertTrue(Assert.java:27)
	at com.cleartrip.platform.accounts.AccountsCommon.validation(AccountsCommon.java:67)
	at com.cleartrip.platform.accounts.API_IVR_Mobile_Date.IVR_Date(API_IVR_Mobile_Date.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- IVR_Date -->
</testsuite> <!-- com.cleartrip.platform.accounts.API_IVR_Mobile_Date -->
