<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking" tests="2" time="628.796" ignored="0" failures="1" timestamp="13 Mar 2019 11:28:36 GMT" skipped="1" hostname="sysadm-PC" errors="0">
  <testcase name="airDom_OW_GDS_NB_Retry_CCBooking_153" time="51.408" classname="testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking">
    <skipped/>
  </testcase> <!-- airDom_OW_GDS_NB_Retry_CCBooking_153 -->
  <testcase name="airDom_OW_GDS_NB_Retry_CCBooking_153" time="577.388" classname="testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking">
    <failure type="java.lang.AssertionError" message="Booking failed after 3 attempts">
      <![CDATA[java.lang.AssertionError: Booking failed after 3 attempts
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking.airDom_OW_GDS_NB_Retry_CCBooking_153(AirDom_OW_GDS_NB_Retry_CCBooking.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- airDom_OW_GDS_NB_Retry_CCBooking_153 -->
</testsuite> <!-- testScriptsPayments.AirDom_OW_GDS_NB_Retry_CCBooking -->
